export const homeObjOne={
    id:'about',
    lightBg:false,
    lightText:true,
    lightTextDesc:true,
    topLine:'About us',
    headline:'Unlimited money gain',
    description:'Doubling and even tripleing your money has never been simpler just with a click of a button',
    buttonLabel:'Get started',
    imgStart:true,
    img:require('./money.png'),
    alt:'money',
    adjustment:false,
    dark:true,
    primary:false,
    show:true,
    darkText:false
}
export const homeObjTwo={
    id:'discover',
    lightBg:true,
    lightText:false,
    lightTextDesc:false,
    topLine:'Just a Click away',
    headline:'How can you get started',
    description:'All u gotta do is bet a specific sum of money on wich face the dice is gonna land if it lands on ur number u can cash out at anytime',
    buttonLabel:'Learn More',
    imgStart:false,
    img:require('./money2.png'),
    alt:'money',
    dark:true,
    adjustment:true,
    primary:true,
    darkText:true,
    show:true
}
export const homeObjThree={
    id:'services',
    lightBg:true,
    lightText:false,
    lightTextDesc:true,
    topLine:'Our Services',
    headline:'We wish for your pockets to be full',
    description:'Just Signup and finaly you can join the rich socity never fear poorness ever again',
    buttonLabel:'Get started',
    imgStart:true,
    adjustment:false,
    img:require('./money3.png'),
    alt:'money',
    dark:true,
    primary:true,
    show:false,
    darkText:true
}
export const homeObjfour={
    id:'signup',
    lightBg:false,
    lightText:true,
    lightTextDesc:true,
    topLine:'Join In now',
    headline:'Fill them pockets',
    description:'You are a click of a button away to join the richtest of the world',
    buttonLabel:'SignUp',
    imgStart:false,
    adjustment:true,
    img:require('./money4.png'),
    alt:'money',
    dark:false,
    primary:false,
    show:true,
    darkText:false
}